### ISSUE TITLE
"ge_link_bulb.device.groovy" doesn't show "off" when the power is removed.

### ISSUE THREAD

**Issue by Muppet1856** [constjs/SmartThings-Devices#6]
I'm thinking this can be fixed by defaulting to off when there is no response, but is there a more elegant way to handle this?

The use case for this involves someone turning off the lamp on the switch (pullcord/knob) and the app still reporting it as "on".

**Comment by Muppet1856** [comment]
Is it possible to have the refresh set it to off and set it back to on if it gets a response?

**Comment by constjs** [comment]
To my knowledge it can't.  There's been a lot of discussion regarding this use case within the Community.  Since ST has accepted and published their new GE device type based on the work the community did, I'm not maintaining this anymore.  ST's code is exactly the same, with some tweaks for logging.
